config/routes.rb
Rails.application.routes.draw do
  resources :stops do
    collection do
      post :import
    end
  end
  root to: "stops#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/stop.rb
class Stop < ApplicationRecord
  require 'csv'

  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|

      stop_hash = row.to_hash
      stop = Stop.where(id: stop_hash["id"])

      if stop.count == 1
        stop.first.update_attributes(stop_hash)
      else
        Stop.create!(stop_hash)
      end # end if !stop.nil?
    end # end CSV.foreach
  end # end self.import(file)

  # def self.as_csv
  #   CSV.generate do |csv|
  #     csv << column_names
  #     all.each do |item|
  #       csv << item.attributes.values_at(*column_names)
  #     end
  #   end
  # end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/stops_controller.rb
class StopsController < ApplicationController
  def index
    @stops = Stop.all
  end

  def import
    Stop.import(params[:file])
    redirect_to root_url, notice: "Data imported"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/stops_helper.rb
module StopsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FormPg</title>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/stops/import.html.erb
<h1>Stops#import</h1>
<p>Find me in app/views/stops/import.html.erb</p>

app/views/stops/index.html.erb
<table>
  <thread>
    <tr>
      <th>Id</th>
      <th>Name</th>
      <th>Description</th>
      <th>Location</th>
      <th>Next direction</th>
    </tr>
  </thread>
  <tbody>
    <% @stops.each do |stop| %>
      <tr>
        <td><%= stop.id %></td>
        <td><%= stop.name %></td>
        <td><%= stop.description %></td>
        <td><%= stop.location %></td>
        <td><%= stop.next_direction %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<div>
<h3>Import a CSV File</h3>
  <%= form_tag import_stops_path, multipart: true do %>
    <%= file_field_tag :file %>
    <%= submit_tag "Import CSV" %>
  <% end %>
</div>